baseURL: http://something-fresh.org/
languageCode: en-us
title: Hugo Fresh Theme
theme: hugo-fresh
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Logo (from /images/logos/___.svg)
  logo: fresh-alt
  font:
    name: "Open Sans"
    sizes: [400,600]
  # Optional color customization
  # color:
  #   primary: "#4FC1EA"
  #   secondary: "#F39200"
  #   accent: "#00efb7"
  hero:
    # Main hero title
    title: Manage. Deploy.
    # Hero subtitle (optional)
    subtitle: Lorem ipsum sit dolor amet is dummy text used by the typography industry
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "#"
    # Hero image (from /images/___)
    image: illustrations/worker.svg
    # Footer logos (from /images/logos/clients/___.svg) and urls
    clientlogos:
    - logo: systek
      url: /#
    - logo: tribe
      url: /#
    - logo: kromo
      url: /#
    - logo: infinite
      url: /#
    - logo: gutwork
      url: /#
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Features
    url: /
  - title: Pricing
    url: /
  - title: Dropdown
    sublinks:
    - title: Dropdown item
      url: /
    - title: Dropdown item
      url: /
    - title: Dropdown item
      url: /
  - title: Log in
    url: /
  - title: Sign up
    url: /
    button: true
  sidebar:
    # Logo (from /images/logos/___.svg)
    logo: fresh-square
    sections:
    - title: User
      icon: user
      links:
      - text: Profile
        url: /
      - text: Account
        url: /
      - text: Settings
        url: /
    - title: Messages
      icon: envelope
      links:
      - text: Inbox
        url: /
      - text: Compose
        url: /
    - title: Images
      icon: image
      links:
      - text: Library
        url: /
      - text: Upload
        url: /
    - title: Settings
      icon: cog
      links:
      - text: User settings
        url: /
      - text: App settings
        url: /
  footer:
    # Logo (from /images/logos/___.svg)
    - logo: fresh-white-alt
    - title: Product
      links:
      - text: Discover features
        link: /
      - text: Why choose our Product?
        link: /
      - text: Compare features
        link: /
      - text: Our Roadmap
        link: /
      - text: Request features
        link: /
    - title: Docs
      links:
      - text: Get started
        link: /
      - text: User guides
        link: /
      - text: Admin guide
        link: /
      - text: Developers
        link: /
    - title: blogroll
      links:
      - text: Latest news
        link: /
      - text: Tech articles
        link: /
      - text: Video blog
        link: /
    - title: Follow Us
      # Social media links (GitHub, Twitter, etc.). All are optional.
      social:
      - link: https://github.com/lucperkins/github-fresh
        # Icons are from Font Awesome
        icon: github
      - link: https://dribbble.com/#
        icon: dribbble
      - link: https://facebook.com/#
        icon: facebook
      - link: https://twitter.com/lucperkins
        icon: twitter
      - link: https://bitbucket.org/#
        icon: bitbucket
      bulmalogo: true
    # You can also use markdown
    # - |
    #   <div class="footer-header">
    #     <h3>Markdown</h3>
    #   </div>
    #
    #   [Here's a link](#)
    #
    #   ![Here's an image](images/logos/fresh.svg)
    #
    #   ---
    #
    #   This is ~~just~~ **some** _text_.
